# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# This CI test and build application, collect dist as artifact
# Also generate project report. Collect test report when test failed.

name: master and release CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 11
        java-package: jdk # The package type (jre, jdk, jdk+fx)
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Upload test reports when FAILED
      uses: actions/upload-artifact@v2.1.4
      with:
        name: test reports
        path: build/reports/tests
      if: ${{ failure() }}
    - name: Build application with Gradle
      run: ./gradlew assembleDist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: artifact
        path: build/distributions/
    - name: Generate project report
      run: ./gradlew projectReport
    - name: Upload project reports
      uses: actions/upload-artifact@v2.1.4
      with:
        name: project reports
        path: build/reports/project
