# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test and Build Application

on:
  push:
    branches:
    - master
    - develop
    - release/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 11
        java-package: jdk # The package type (jre, jdk, jdk+fx)
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Upload test reports when FAILED
      uses: actions/upload-artifact@v2.1.4
      with:
        name: test reports
        path: build/reports/tests
      if: ${{ failure() }}
    - name: Build application with Gradle
      run: ./gradlew assembleDist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: artifact
        path: build/distributions/
    - name: Generate project report
      run: ./gradlew projectReport
    - name: Upload project reports
      uses: actions/upload-artifact@v2.1.4
      with:
        name: project reports
        path: build/reports/project
